sudo: required

language: bash

services:
  - docker

script:
  - bash build.sh

before_deploy:
  - docker build . -t joshwyant/gcc-cross

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
  